# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 06:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('link', models.CharField(blank=True, max_length=180, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events_events',
            },
        ),
        migrations.CreateModel(
            name='EventsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('link', models.CharField(blank=True, max_length=180, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'events_events_history',
            },
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('short_name', models.CharField(blank=True, max_length=2, null=True)),
                ('link', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(choices=[('PL', 'Place'), ('TS', 'Ticket Seller'), ('MP', 'Media Partner')], max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events_platforms',
            },
        ),
        migrations.AlterUniqueTogether(
            name='platforms',
            unique_together=set([('name', 'category')]),
        ),
        migrations.AddField(
            model_name='eventshistory',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Platforms'),
        ),
        migrations.AddField(
            model_name='events',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Platforms'),
        ),
        migrations.AlterUniqueTogether(
            name='events',
            unique_together=set([('platform', 'name', 'link', 'date')]),
        ),
    ]
