# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170822_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventsHistory',
            new_name='EventHistory',
        ),
    ]
